# Generated by Django 3.2.4 on 2021-08-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField(max_length=2)),
                ('slot_1', models.CharField(max_length=255)),
                ('slot_2', models.CharField(max_length=255)),
                ('slot_booked', models.BooleanField(default=False)),
            ],
        ),
    ]
