# Generated by Django 3.2.4 on 2021-08-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='id',
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
