# Generated by Django 3.2.4 on 2021-08-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210817_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
